repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.2
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/djlint/djLint
  rev: v1.34.1
  hooks:
    - id: djlint-reformat-jinja
      files: "app/templates"
      extension: "html"
    - id: djlint-jinja
      files: "app/templates"
      extension: "html"
